### ISSUE TITLE
Merge Traffic Volume

### ISSUE THREAD

**Issue by pichot** [pichot/citibike-publicspace#7]
https://datahub.cusp.nyu.edu/dataset/p424-amsu

**Comment by kristikorsberg** [comment]
Hi Kay, here is a website for NYS DOT with GIS data:
https://gis.ny.gov/gisdata/inventories/results.cfm?themeIDs=24
I would check out the shape files inside the NYS Average Annualized Daily Traffic

**Comment by pichot** [comment]
Is there a reason why we're using the State's data rather the City's data? https://data.cityofnewyork.us/NYC-BigApps/Traffic-Volume-Counts-2012-2013-/p424-amsu/data

**Comment by kayzhou22** [comment]
https://www.dot.ny.gov/tdv

shapefiles are:
TDV_Shapefile_Short_Counts_2014.zip
TDV_Shapefile_Continuous_Counts_2014.zip

**Comment by kayzhou22** [comment]
The reason of getting too few intersections of bike stations(buffered) and traffic counts is that the number of traffic volume counters are fewer than the number of citi bike stations. Comparing the locations of the counters with the bike stations on the map, the counters are not as evenly distributed as the citi bike stations, and obviously there are more on the roads with heavier traffic (ie. 53rd street in midtown...)  
I am going to show this to our GIS instructor this afternoon and see if he has any suggestion.

Alternatively, I am considering using CO2 emission level if I can find the applicable data set. 
@dfay88  Does your street quality data contain similar attributes like street's air pollution level?

**Comment by kayzhou22** [comment]
@pichot @kristikorsberg @dfay88 @aaron-15 
Hello! Let's take a look at the locations of the citi-bike stations and the traffic counters.
If we all feel that there should be traffic volume data for more bike stations, I will try to find something else. :(

![trafficcounts_location](https://cloud.githubusercontent.com/assets/10051860/19441359/80d3262e-9453-11e6-8e72-744e5714e247.jpg)
