### ISSUE TITLE
Merge Subway Entrances

### ISSUE THREAD

**Issue by pichot** [pichot/citibike-publicspace#9]
https://data.cityofnewyork.us/Transportation/Subway-Entrances/drex-xx56

**Comment by aaron-15** [comment]
I checked the csv file, it has 4 columns which have the following:
1. Coordinates (lat, long)
2. Name
3. URL
4. Line (Routes)

Wanted to know the format in which we are using the data, csv/json/geojson

**Comment by pichot** [comment]
Just to note it here, we're saving to a CSV for the final data.
